### ISSUE TITLE
Minimum requirements for CRX-10iA/L

### ISSUE THREAD

**Issue by pucciland95** [UofI-CDACS/fanuc_ethernet_ip_drivers#13]
Hi,

soon, it will arrive in our lab a new CRX-10iA/L, and we are planning to use it with ROS/ROS2 and, if we have time, contribute to this repo.
Fanuc is asking us whether we need in the robot some "additional configuration". Since I am not an expert of the FANUC ecosystem, may I ask you whether we need some particular configurations to make it work with ROS/ROS2? 
Are there some modules for external guidance, like ABB ecosystem (EGM)?

Let us know

**Comment by JamesL-dev** [comment]
Hello,

The drivers we specifically use for the ethernet/IP setup are:
Ethernet/IP EDA R822
Ethernet/IP Scanner R785
Ethernet/IP I/O Adp. R538
EthernetIP I/O scan R540

These came default on our CRX-10iA/L robots and is all that is required for communication.
