### ISSUE TITLE
Issues with the teach pendant code

### ISSUE THREAD

**Issue by Andrew-Raz-ACRV** [UofI-CDACS/fanuc_ethernet_ip_drivers#18]
Hi,

I am interested in using the work you guys have done on the ROS 2 Fanuc driver to stream waypoints to an LRMate 200ic robot and control a welder via robot I/O. So far I have been trying to figure out how to use the ethernet IP driver you developed. When I try running the .TP program ros2_eip_mainv2.tp, my robot aborted it due to code format. Is there something missing? Maybe I need to compile the TP program from source to make it work for my machine.

Here is a screenshot of the teach pendant error message I am receiving:
![image](https://github.com/UofI-CDACS/fanuc_ethernet_ip_drivers/assets/27539224/1a9077c4-1f80-48d9-9f86-3f718a3cc9ab)

**Comment by JamesL-dev** [comment]
I am not familiar with that robots TP coding style. The overall Idea should be the same. As long as you map your registers for reading/writing you can most likely come up with a similar script for your robots.
