### ISSUE TITLE
Question regarding setup on the robot controller side

### ISSUE THREAD

**Issue by LouKordos** [UofI-CDACS/fanuc_ethernet_ip_drivers#19]
Hi, first of all thank you for creating this package! I'm trying to do position control and position readout of the FANUC CRX-10A for a german car manufacturer and wnat to use this package. I'm still a beginner in everything FANUC related so I'm having trouble setting up the controller to communicate with the robot.

So far I've just run your cartesian example with the correct IP and the position readout worked out of the box, but writing to the position does not do anything. Since the documentation is not really existant if I may say so, could you provide some insight into how to set this up?

So far I've installed the background and foreground programs and run them, but if I'm not mistaken the registers used in the python code do not match the ones in the TP programs (which are still called ROS_... btw). The TP programs do some register manipulation but the Python code just updates Position register 1 so that's what confuses me.

I've read the word doc and the registers mentioned are defined on my controller (although the word doc doesn't mention the DO and DI used in V2). Do I need to do anything else on the robot? I've configured the background program as BG Logic and it runs, then I run the foreground program in AUTO mode and then I should be able to use the same script that writes to the position register to move the robot or not?

**Comment by known-blue** [comment]
Hi! I'm assuming you're the one who reached out on LinkedIn, if not ignore that fact, but here is some similar advice for anyone else with this issue: 

I’m assuming you are using the ‘writeCartesianPositionRegister()' function? To get the robot to move (which isn’t in all examples that use that function) you have to set the R[1] register after you populate PR (proper example here; examples/cartesian/ether_IP_cartesian_example.py ) this is so you can test that you can properly set the IO without causing the robot to move until you are ready (aka if you wanted to set speed first or realized you put the wrong value, etc...) 

I also highly recommend abstracting a bit more and using the robot_controller class that’s provided, it does list management and that silly R register for you; you just give it a coordinate and it does the rest.

**Comment by LouKordos** [comment]
Hi, thank you for the quick reply, yeah that was me on LinkedIn :)

I've managed to get it to move now, I went through the scripts again but still have a few questions:

1. If I understand correctly, the backgroud program is completely irrelevant for basic position readout and movement? The python code writes to the PR and the activation register 1 and the TP foreground program just moves to that position right?

2. Is the background program just for grippers etc.?

3. I am doing some dynamic movements and want to get the highest update frequency possible, that is why I did not use your abstraction ``robot_controller`` and tried getting the more "low-level" version to work. However with high speed movements and a circular motion as a test, it doesn't really move in a smooth circular motion anymore, but rather it lags behind and only moves to certain positions. I even set the angular frequency to be ``omega=vel_limit/amplitude`` which should be correct but it still lags behind. My code is attached below but I think the biggest performance improvement would come from disabling the register 1 check and just continually writing to PR[1]. Until now, I've used a while loop to poll the current register state since the TP program resets it when the movement is done. Do I have to worry about corrupted write errors/race conditions on the PR if I write to it with ~500Hz and the TP program just consists of a loop with CNT to that PR?
The "choppiness" could also be due to the rather high 8ms cycle time though, I'd love to hear your thoughts. 

Basically my goal is to have the robot simply accept position setpoints at the highest frequency possible and move to those with a set velocity so that I can generate trajectories in python/cpp and then feed those to the robot.

4. Since I'm using this for a rather quick pick and place with force control, I would probably need CNT movements for going close to the place spot, then switch to fine and lower it until I get a force feedback. Is the smartest way of doing this to just add another if check in the TP program for say R[2] and then set that to 1 or 0 depending on if I want FINE or CNT? And then to stop when the force threshold is exceeded, just set R[1] to 0.

Code:

```py
#/usr/bin/env python3


import sys
import signal
# sys.path.append('./pycomm3/pycomm3')
import pycomm3
import random
import math
import time
sys.path.append('../FANUC-Ethernet_IP_Drivers/src/')
import FANUCethernetipDriver
exit_flag = False

def signal_handler(signal, frame):
   # print("Caught Interrupt signal, setting exit flag.")
   global exit_flag
   exit_flag = True

   # Tell robot to stop moving
   enable_register = 1
   value = 0
   _ = FANUCethernetipDriver.writeR_Register(ip, enable_register, value)

signal.signal(signal.SIGINT, handler=signal_handler)

ip = "10.36.12.3"
dt = 0.1
velocity_limit = 900
T = 2 # seconds per cycle
omega = 2*math.pi/T # angular frequency
amplitude = 200 # mm
# omega = velocity_limit / amplitude

def set_velocity_limit(ip, vel_limit):
   velocity_register = 5
   return FANUCethernetipDriver.writeR_Register(ip, velocity_register, vel_limit)

def move_to_pos_sync(ip, position):
   global exit_flag
   # Set position used in TP program
   PR_index = 1
   _ = FANUCethernetipDriver.writeCartesianPositionRegister(ip, PR_index, position)
  
   # Set R[1] to 1 so that TP program actually moves to the position.
   enable_register = 1
   value = 1
   _ = FANUCethernetipDriver.writeR_Register(ip, enable_register, value)
   # time.sleep(0.1)
   # In its current version, the foreground TP program will block until the position is reached
   # and then R[1] will be set to 0 again, indicating the movement has finished.
   while FANUCethernetipDriver.readR_Register(ip, enable_register) and not exit_flag:
       print("\rWaiting for movement to finish...", end="", flush=True)
       time.sleep(0.001)
  
   print("")

def move_to_safe_pos(ip):
   # Hardcoded for specific setup, UTOOL, UFRAME, X, Y, Z, W, P, R and some other stuff, see FANUC Ethernet IP driver code: https://github.com/UofI-CDACS/fanuc_ethernet_ip_drivers/blob/84c6baf4d03e8c53d1fd31cd346c10445dd6645c/src/FANUCethernetipDriver.py#L125
   safe_pos = [1, 1, 20, 250.0, 400.0, -179.95179748535156, 0.06449063867330551, -90.03273010253906, 0, 0, 0, 52, 0.0, 0.0, 0.0, [1, 0, 1, 0, 64, 141, 198, 192, 43, 63, 203, 67, 0, 81, 194, 67, 169, 243, 51, 195, 171, 19, 132, 61, 194, 16, 180, 194, 0, 0, 0, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
   print(f"current_pos={FANUCethernetipDriver.returnCartesianCurrentPostion(ip)[2:8]}\tsafe_pos={safe_pos[2:8]}")
   if input("Press enter if the above safe pos is correct.") == "":
       move_to_pos_sync(ip=ip, position=safe_pos)
       print("Moved to predefined safe position.")

# TODO: Implement circular buffer for smoother movements (might not be necessary for pick and place though)
# TODO: Use another register in TP to determine if movement should use "FINE" or "CNTXX" command

set_velocity_limit(ip=ip, vel_limit=300)
move_to_safe_pos(ip=ip)
time.sleep(0.1)
set_velocity_limit(ip=ip, vel_limit=velocity_limit)

# UTOOL, UFRAME, X, Y, Z, W, P, R
initial_pos = FANUCethernetipDriver.returnCartesianCurrentPostion(ip)
print("initial_pos=", initial_pos)

pos1 = initial_pos.copy()
pos1[2] += 600
pos1[3] += 200

for i in range(10):
   if not exit_flag:
       expected_duration = math.sqrt((initial_pos[2]-pos1[2])**2+(initial_pos[2]-pos1[2])**2+(initial_pos[2]-pos1[2])**2) / velocity_limit
       start = time.time()
       move_to_pos_sync(ip=ip, position=pos1)
       end = time.time()
       actual_duration = (end - start)
       print(f"i={i}\texpected_duration={expected_duration:.4f}\tactual_duration={actual_duration:.4f}\texp-actual={((expected_duration-actual_duration)*1000.0):.4f}[ms]\tpos_error_max_vel={((expected_duration-actual_duration)*velocity_limit):.4f}[mm]")
       time.sleep(0.01)
       move_to_pos_sync(ip=ip, position=initial_pos)

# UTOOL, UFRAME, X, Y, Z, W, P, R
initial_pos = FANUCethernetipDriver.returnCartesianCurrentPostion(ip)
print("initial_pos for circular movement=", initial_pos)
desired_pos = initial_pos.copy()

start = time.time()

for i in range(500):
   if not exit_flag:
       t = time.time() - start
       desired_pos[2] = initial_pos[2] + amplitude * math.cos(omega*t) # - 150
       desired_pos[3] = initial_pos[3] + amplitude * math.sin(omega*t) # - 150
       desired_pos[4] = initial_pos[4]
       # time.sleep(0.1)
       print(f"t={t}\tdesired_pos={desired_pos[2:8]}")
       move_to_pos_sync(ip, desired_pos)
```

**Comment by LouKordos** [comment]
To add to this, I've also considered adding a "circular buffer" with 3 PRs that are all continually updated so that the robot has a bit of look-ahead when it's planning the movement but I don't think this is going in the right direction of my goal explained at the end of point 3. Since I'm still very much a beginner with this robot, if you have any ideas on how to achieve this, I'm all ears :)

**Comment by JamesL-dev** [comment]
Hello yes, the background program is only for grippers and peripherals so yes you are correct. You just need the MAIN driver running for movement functionality.
 I am interested in your proposed technique to send coordinates at the highest frequency possible and would love to see your work on the subject. This project currently does not have dedicated people working on it so development is slow.
I look forward to hearing about any solution you may come up with.
