### ISSUE TITLE
Does this project support fax machines?

### ISSUE THREAD

**Issue by hunterdhawkins** [UofI-CDACS/fanuc_ethernet_ip_drivers#21]
![fanuc_fax_machine](https://github.com/user-attachments/assets/8c979251-12ea-42ed-91d0-c4f3c4aa273e)
I am currently trying to remotely control my Fanuc fax machine. I was wondering if this library would be of assistance.  When providing coordinates the machine does not seems to move.

**Comment by hunterdhawkins** [comment]
@JamesL-dev

**Comment by JamesL-dev** [comment]
Yes
