### ISSUE TITLE
Broken Examples Directory `import ...` Statements

### ISSUE THREAD

**Issue by grwells** [UofI-CDACS/fanuc_ethernet_ip_drivers#8]
In both the [dev](UofI-CDACS/fanuc_ethernet_ip_drivers/tree/dev) and [master](UofI-CDACS/fanuc_ethernet_ip_drivers/tree/master) branches examples import statements were broken as part of the refactoring of the directory structure. This meant that it was impossible to run the examples in place, they had to be copied outside the submodule and the imports refactored.

If we want to have examples run inside `examples/` the easiest method would be adding the following to the top of each example script:

```python
import sys
sys.path.append('..')

# then import with
from .src.robot_controller import robot
```

**Comment by known-blue** [comment]
Similar to your recommendation, this has been done in the dev branch to all the examples:
```python
import sys
sys.path.append('../../src') # or sys.path.append('../src') depending on how nested it is
from robot_controller import robot
```
This should hopefully solve the issues.

**Comment by grwells** [comment]
Another year older, another year wiser. We should probably just restructure this to match the [standard python package](https://docs.python-guide.org/writing/structure/) .

Based on that link, I think there are several main improvements:
1. Put source files in the root. Submodules/packages in folders in the root.
2. Put `__init__.py` in the root to mark as a package and handle imports.
3. Provide a `tests/` directory for unit testing, etc. Use a `tests/context.py` file to handle imports.
4. Make sure the examples in `examples/` can be run as if they are just importing the package. In other words, don't need to use os path appending to find source files.

After considering these changes with @JamesL-dev we would also probably be best off releasing a version of the repo as it is now before we make structure changes that would break imports for users.

**Comment by JamesL-dev** [comment]
Agreed.
